### ISSUE TITLE
Clear and easy-to-understand game structure 

### ISSUE THREAD

**Issue by JOCPhys** [Gerbil1511/Science-Shuffle#11]
As a player I want a clear and easy-to-understand game structure so that I can focus on learning rather than figuring out how to play

**Acceptance Criteria:**

- [x] The game instructions should be clear and accessible.
- [x] The layout of the game should be intuitive, with clearly labelled start button.
- [x] Pressing the start button should initialize the game and present the player with the card grid.

**Tasks:**

- [x] Implement a clear instructions statement
- [x] Ensure start button and game sections are labelled and positioned logically.
- [x] Link the start button to the game initialization function.
