### ISSUE TITLE
Arrangement and display of cards

### ISSUE THREAD

**Issue by JOCPhys** [Gerbil1511/Science-Shuffle#15]
As a player I want to see a grid of cards face down so that I can start matching pairs 

**Acceptance Criteria:**  

- [x] The card grid should display all cards face down at the beginning of the game.  
- [x] The layout of the grid should be neat and organized.  
- [x] Players should be able to click on any card to start flipping them.  

**Tasks:**  

- [x] Create a grid layout to display the cards.  
- [x] Ensure all cards are displayed face down at the start.  
- [x] Implement the functionality to allow players to click and flip cards.
