### ISSUE TITLE
Card matching functionality

### ISSUE THREAD

**Issue by JOCPhys** [Gerbil1511/Science-Shuffle#18]
As a player I want to see the cards flip back over if they do not match so that I can try again to find a matching pair

**Acceptance Criteria:**

- [x] Non-matching cards should flip back over after a brief delay.
- [x] The delay should be long enough for players to see the cards but short enough to keep the game’s pace.
- [x] As difficulty increases, increase the length in the time delay to enable effective study
- [x] Matching cards should remain face-up until the end of the game.

**Tasks:**

- [x] Implement logic to compare the clicked cards.
- [x] Add a delay mechanism for various difficulties before flipping non-matching cards back over.
- [x] Ensure that matching cards remain face-up and non-matching cards flip back correctly.
