### ISSUE TITLE
Feedback message when all pairs matched

### ISSUE THREAD

**Issue by Gerbil1511** [Gerbil1511/Science-Shuffle#19]
As a player, I want to see a message when I have matched all pairs so that I know I have completed the game.

**Acceptance Criteria:**

- [x] Display a message when all pairs have been matched.
- [x] Ensure the message is clear and visible.

**Tasks:**

- [x] Create a function to check if all pairs are matched.
- [x] Design a message to display upon game completion.
- [x] Implement logic to display the message when the game is completed.
