### ISSUE TITLE
See a time counter

### ISSUE THREAD

**Issue by Gerbil1511** [Gerbil1511/Science-Shuffle#20]
As a player, I want to see a timer counting up so that I can see how long it takes me to complete the game.

**Acceptance Criteria:**

- [x] A timer should start at the beginning of the game and count up.
- [x] The timer should be visible on the screen.
- [x] The timer should stop when all pairs are matched.

**Tasks:**

- [x] Add a timer element to the HTML.
- [x] Implement a JavaScript function to start and update the timer.
- [x] Ensure the timer stops when the game is completed.
