### ISSUE TITLE
Number of attempts counter

### ISSUE THREAD

**Issue by Gerbil1511** [Gerbil1511/Science-Shuffle#21]
As a player, I want to see a counter for the number of attempts I have made so that I can track my progress and try to improve.

**Acceptance Criteria:**

- [x] Display a counter that increments with each attempt.
- [x] The counter should be visible on the screen.
- [x] Reset the counter at the start of each game.

**Tasks:**

- [x] Add a counter element to the HTML.
- [x] Implement a JavaScript function to update the counter with each attempt.
- [x] Ensure the counter resets when the game is restarted.
