### ISSUE TITLE
Instructions for how to play the game

### ISSUE THREAD

**Issue by Gerbil1511** [Gerbil1511/Science-Shuffle#24]
As a player, I want to have access to instructions, so that it’s easy to understand how to play the game.

**Acceptance Criteria:**

- [ ] Include a section/modal with clear and concise instructions.
- [ ] Ensure the instructions are easily accessible from the main game interface.

**Tasks:**

- [ ] Write clear and concise instructions for the game.
- [ ] Add an instructions section to the HTML for a modal.
- [ ] Implement logic to display with javascript and hide instructions as needed.
